paths:
  train_json: /kaggle/working/data/clean/train_clean.json
  val_json: /kaggle/working/data/clean/val_clean.json
  references_json: /kaggle/working/data/clean/references.json
  train_image_dir: /kaggle/input/datasets/ayaanmustafa/vrs-bench/vrsbench_data/Images_train/Images_train
  val_image_dir: /kaggle/input/datasets/ayaanmustafa/vrs-bench/vrsbench_data/Images_val/Images_val
  encoder_ckpt: /kaggle/working/VRSbench_Project/checkpoints/RemoteCLIP-ViT-B-32.pt
  output_root: /kaggle/working/runs
data:
  max_caption_len: 110
  train_subset: null
  val_subset: null
train:
  batch_size: 16
  num_workers: 4